//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case_Handler
    {
        public Case_Handler()
        {
            this.Evidences = new HashSet<Evidence>();
            this.Interview_Invite = new HashSet<Interview_Invite>();
            this.Investigation_Interview = new HashSet<Investigation_Interview>();
            this.InvestigationCase1 = new HashSet<InvestigationCase1>();
            this.Evidence_Request = new HashSet<Evidence_Request>();
        }
    
        public string CH_Employee_ID { get; set; }
        public string Case_Handler_Type { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Evidence> Evidences { get; set; }
        public virtual ICollection<Interview_Invite> Interview_Invite { get; set; }
        public virtual ICollection<Investigation_Interview> Investigation_Interview { get; set; }
        public virtual ICollection<InvestigationCase1> InvestigationCase1 { get; set; }
        public virtual ICollection<Evidence_Request> Evidence_Request { get; set; }
    }
}
