//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseType
    {
        public CaseType()
        {
            this.InvestigationCase1 = new HashSet<InvestigationCase1>();
        }
    
        public int C_Case_Type_ID { get; set; }
        public string Case_Type { get; set; }
    
        public virtual ICollection<InvestigationCase1> InvestigationCase1 { get; set; }
    }
}
