//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Interview_Invite = new HashSet<Interview_Invite>();
            this.Investigation_Interview = new HashSet<Investigation_Interview>();
            this.Termination_Request = new HashSet<Termination_Request>();
            this.Interview_Invite1 = new HashSet<Interview_Invite>();
            this.Investigation_Interview1 = new HashSet<Investigation_Interview>();
            this.Evidence_Request = new HashSet<Evidence_Request>();
        }
    
        public string Employee_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email_Address { get; set; }
        public string Password { get; set; }
        public string Mobile_Number { get; set; }
        public string Region { get; set; }
        public System.DateTime DOB { get; set; }
        public string Job_Title { get; set; }
        public string Employee_Grade { get; set; }
        public string Employee_Type { get; set; }
        public string Department_ID { get; set; }
    
        public virtual AccusedEmp AccusedEmp { get; set; }
        public virtual Case_Handler Case_Handler { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Interview_Invite> Interview_Invite { get; set; }
        public virtual ICollection<Investigation_Interview> Investigation_Interview { get; set; }
        public virtual Requester Requester { get; set; }
        public virtual ICollection<Termination_Request> Termination_Request { get; set; }
        public virtual ICollection<Interview_Invite> Interview_Invite1 { get; set; }
        public virtual ICollection<Investigation_Interview> Investigation_Interview1 { get; set; }
        public virtual ICollection<Evidence_Request> Evidence_Request { get; set; }
    }
}
