//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evidence
    {
        public int Evidence_ID { get; set; }
        public string Evidence_Type { get; set; }
        public System.DateTime Evidence_Date { get; set; }
        public string Evidence_Details { get; set; }
        public byte[] Evidence_Document { get; set; }
        public string Requester_ID { get; set; }
        public string Case_Handler_ID { get; set; }
        public int Case_ID { get; set; }
    
        public virtual Case_Handler Case_Handler { get; set; }
        public virtual InvestigationCase1 InvestigationCase1 { get; set; }
    }
}
