//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview_Invite
    {
        public Interview_Invite()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int Interview_Invitation_ID { get; set; }
        public System.DateTime Interview_Invitation_Date { get; set; }
        public string Interview_Invitation_Time { get; set; }
        public string Interview_Invitation_Location { get; set; }
        public System.DateTime Interview_Invitation_Date_Sent { get; set; }
        public string Interview_Invitation_Acceptance { get; set; }
        public string Case_Handler_ID { get; set; }
        public string Interview_Invitation_Invitee { get; set; }
        public string Interview_Invitation_Details { get; set; }
        public int Case_ID { get; set; }
    
        public virtual Case_Handler Case_Handler { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual InvestigationCase1 InvestigationCase1 { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
