//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestigationCase1
    {
        public InvestigationCase1()
        {
            this.Evidences = new HashSet<Evidence>();
            this.Interview_Invite = new HashSet<Interview_Invite>();
            this.Investigation_Interview = new HashSet<Investigation_Interview>();
            this.Termination_Request = new HashSet<Termination_Request>();
            this.Evidence_Request = new HashSet<Evidence_Request>();
        }
    
        public int Case_ID { get; set; }
        public Nullable<int> Case_Type { get; set; }
        public System.DateTime Case_Start_Date { get; set; }
        public Nullable<System.DateTime> Case_End_Date { get; set; }
        public Nullable<int> Case_Status { get; set; }
        public string Case_Details { get; set; }
        public string Case_Duration { get; set; }
        public Nullable<int> Case_Verdict { get; set; }
        public string Employee_ID { get; set; }
        public string Case_Handler_ID { get; set; }
        public string Requester_ID { get; set; }
    
        public virtual Case_Handler Case_Handler { get; set; }
        public virtual Case_Status Case_Status1 { get; set; }
        public virtual Case_Verdict Case_Verdict1 { get; set; }
        public virtual CaseType CaseType { get; set; }
        public virtual ICollection<Evidence> Evidences { get; set; }
        public virtual ICollection<Interview_Invite> Interview_Invite { get; set; }
        public virtual ICollection<Investigation_Interview> Investigation_Interview { get; set; }
        public virtual Requester Requester { get; set; }
        public virtual ICollection<Termination_Request> Termination_Request { get; set; }
        public virtual ICollection<Evidence_Request> Evidence_Request { get; set; }
    }
}
