//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investigation_Interview
    {
        public Investigation_Interview()
        {
            this.QuestionsAnswers = new HashSet<QuestionsAnswer>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int Investigation_Interview_ID { get; set; }
        public System.DateTime Investigation_Interview_Date { get; set; }
        public string Investigation_Interview_Time { get; set; }
        public string Investigation_Interview_Location { get; set; }
        public string Investigation_Interview_Memo { get; set; }
        public string Investigation_Interview_Interviewee_ID { get; set; }
        public string Investigation_Interview_Interviewer_ID { get; set; }
        public int Case_ID { get; set; }
    
        public virtual Case_Handler Case_Handler { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual InvestigationCase1 InvestigationCase1 { get; set; }
        public virtual ICollection<QuestionsAnswer> QuestionsAnswers { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
