//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_2
    {
        public string Case_Status { get; set; }
        public string Case_Verdict { get; set; }
        public string Case_Type { get; set; }
        public string Expr1 { get; set; }
        public int Expr2 { get; set; }
        public System.DateTime Case_Start_Date { get; set; }
        public Nullable<System.DateTime> Case_End_Date { get; set; }
        public string Case_Details { get; set; }
        public string Case_Duration { get; set; }
        public string Employee_ID { get; set; }
        public string Expr3 { get; set; }
        public int Evidence_ID { get; set; }
        public string Evidence_Type { get; set; }
        public System.DateTime Evidence_Date { get; set; }
        public string Evidence_Details { get; set; }
        public byte[] Evidence_Document { get; set; }
        public System.TimeSpan Expr4 { get; set; }
        public string Expr5 { get; set; }
        public string Expr6 { get; set; }
        public string Expr7 { get; set; }
        public int Expr8 { get; set; }
        public System.DateTime Investigation_Interview_Date { get; set; }
    }
}
