//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_4
    {
        public int Case_ID { get; set; }
        public System.DateTime Case_Start_Date { get; set; }
        public Nullable<System.DateTime> Case_End_Date { get; set; }
        public string Case_Details { get; set; }
        public string Case_Duration { get; set; }
        public string Employee_ID { get; set; }
        public string Case_Handler_ID { get; set; }
        public string Requester_ID { get; set; }
    }
}
